recover:
   application:
      list : alipay-service,wechat-service,pay-service
   serializer :
      support: kryo
   retry :
      max: 10
   db:
      driver :  com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/tx?useUnicode=true&amp;characterEncoding=utf8
      username: root
      password: 123456
