server:
   port: 8888
   context-path: /admin

spring:
   application:
      name: raincat-admin
   profiles:
     active: db

tx:
  admin :
    userName : admin
    password : admin
  redis:
    hostName: localhost
    port : 6379
    #password:
    cluster : false
      # nodes: 127.0.0.1:70001;127.0.1:7002
      # redirects: 20

accept:
  apps:
    server:
      type[0]: property
      type[1]: eureka
      type[2]: unaccept
    eureka:
      url: http://localhost:8761/eureka
      intervalTime: 30
