server:
  port: 8883
  contextPath: /wechat-service
  address: 0.0.0.0


spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.78:3306/wechat?useUnicode=true&characterEncoding=utf8
        username: xiaoyu
        password: Wgj@555888
    application:
      name: wechat-service

mybatis:
  type-aliases-package: com.happylifeplat.transaction.tx.springcloud.sample.wechat.entiy
#${random.int[9000,9999]}
eureka:
 client:
     serviceUrl:
       defaultZone: http://localhost:8761/eureka/
wechat-service :
   ribbon.NFLoadBalancerRuleClassName : com.netflix.loadbalancer.RandomRule


