server:
  port: 8881
  contextPath: /pay-service
  address: 0.0.0.0


spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/pay?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
    application:
      name: pay-service

mybatis:
  type-aliases-package: com.raincat.springcloud.sample.pay.entiy
#${random.int[9000,9999]}
eureka:
 client:
     serviceUrl:
       defaultZone: http://localhost:8761/eureka/

pay-service :
   ribbon :
     NFLoadBalancerRuleClassName : com.netflix.loadbalancer.RandomRule
     MaxAutoRetriesNextServer : 0


logging:
            level:
                root: info
                com.raincat.core : debug
            path: "./logs"