server:
  port: 8883
  contextPath: /wechat-service
  address: 0.0.0.0


spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/wechat?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
    application:
      name: wechat-service

mybatis:
  type-aliases-package: com.raincat.springcloud.sample.wechat.entiy
#${random.int[9000,9999]}
eureka:
 client:
     serviceUrl:
       defaultZone: http://localhost:8761/eureka/
wechat-service :
   ribbon.NFLoadBalancerRuleClassName : com.netflix.loadbalancer.RandomRule


logging:
            level:
                root: info
                com.raincat.core : debug
            path: "./logs"

